name: Continuous Integration with GitHub Actions
on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/MiguelGit20/holbertonschool-validation.git
      - run: cd module3_task0/
      - run: make help
